###########服务启动端口号#########
server:
  port: 8010
  servlet:
    ##########项目访问路径##########
    context-path: /stockquant-api
spring:
  main:
    # 解决Bean重复定义问题
    allow-bean-definition-overriding: true
  application:
    name: stockquant-consumer
dubbo:
  # 配置服务信息
  application:
    name: stockquant-consumer
    # 禁用QOS同一台机器可能会有端口冲突现象
    qos-enable: false
    qos-accept-foreign-ip: false
  # 配置注册中心
  registry:
    address: nacos://ip:9090
  # 设置超时时间
  consumer:
    timeout: 30000
  protocol:
      name: dubbo


nacos:
  config:
    server-addr: ip:port
##########日志输出路径##########
logging:
  level:
    root: info
    com:
      taotr: info
  file:
    path: /fiac-logs/fiac.log
##########  中证易签 配置##########
zzyq:
  ipconfig: https://ip/api/OPSP/rqCode/{rqCode}/transaction
  accesskeysecret: accesskeysecret
  accesskeyid: accesskeyid
  mrdebuggermodel: true
